# Generated by Django 5.0 on 2024-06-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_alter_juego_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('juego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='click_count', to='juegos.juego')),
            ],
            options={
                'verbose_name': 'Click Count',
                'verbose_name_plural': 'Click Counts',
            },
        ),
    ]
